### ISSUE TITLE
values.local.yaml outdated on chart Jenkinsio readme 

### ISSUE THREAD

**Issue by SarathChandra24** [jenkins-infra/helm-charts#1069]
### Describe your use-case which is not covered by existing documentation.

Current values.local.yaml in readme 

```yaml
ingress:
  enabled: true
  hosts:
    - host: local.jenkins.io
      paths:
        - path: /
          service:
            name: jenkinsio
            port:
              number: 80
        - path: /zh/
          service:
            name: jenkinsio-zh
            port:
              number: 80

htmlVolume:
  hostPath:
    path: /host

zhHtmlVolume:
  hostPath:
    path: /hostzh
```

but this will throw the following error
```
Error: INSTALLATION FAILED: 1 error occurred:
	* Ingress.extensions "jenkinsio" is invalid: [spec.rules[0].http.paths[0].backend.service.name: Required value, spec.rules[0].http.paths[1].backend.service.name: Required value
```
After looking at the following [ingress.yaml](https://github.com/jenkins-infra/helm-charts/blob/main/charts/jenkinsio/templates/ingress.yaml#L38) values should have .serviceName
Ideally values.local.yaml should be like this

```yaml
ingress:
  enabled: true
  hosts:
    - host: local.jenkins.io
      paths:
        - path: /
          serviceName: jenkinsio
          service:
            name: jenkinsio
            port:
              number: 80
        - path: /zh/
          serviceName: jenkinsio-zh
          service:
            name: jenkinsio-zh
            port:
              number: 80

htmlVolume:
  hostPath:
    path: /host

zhHtmlVolume:
  hostPath:
    path: /hostzh
```

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

 https://github.com/jenkins-infra/kubernetes-management/blob/b101a0c16479bff55d03c9c10db92df2ee28dfbc/config/jenkinsio.yaml#L12-L15
