### ISSUE TITLE
(jenkins-jobs) bug: Top-level multibranch pipeline generates empty id

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helm-charts#110]
With the following values:

```yaml
jobsDefinition:
  jenkins-k8s:
    name: Jenkins K8S
    description: Multibranch test
```

The generated job-dsl has empty ids for the multibranch job:

```groovy
jobs:      
  - script: >
      
      multibranchPipelineJob('') {
        triggers {
          periodicFolderTrigger {
            interval('2h')
          }
        }
      
        branchSources {
          branchSource {
            source {
              github {
                id('<nil>')
// ...
```
